import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import DataTable from 'react-data-table-component';
import { useEffect, useState } from 'react';

export interface Datapair {
  provider : String
  min_amount : String
  max_amount : String
  fee : String
  rate : String
  pair : String
  url : String
}

const Home: NextPage = () => {

  const [tableData, setTableData] = useState<Datapair[]>([]);
  const [testText, settestText] = useState<String>("");

  useEffect(() => {
    var pairData : Datapair[] = [];
    fetch('https://lnsov.ml:9001/getpairs')
      .then(response => response.json())
      .then(data => {
        let pairs = data.pairs;
        Object.entries(pairs).map(([key, value] : any) => {
          pairData.push({
            fee : value.fees.percentage + "%",
            max_amount : value.limits.maximal,
            min_amount : value.limits.minimal,
            pair : key,
            provider : "https://lnsov.vercel.app/",
            rate : value.rate,
            url : "https://lnsov.ml:9001",
          });
      });
    });
    //setTableData({...pairData});
    setTableData(pairData);
    console.log(pairData);
  }, []);

  const columns = [
    {
      name: 'Fee',
      selector: row => row.fee,
    },
    {
      name: 'Max amount',
      selector: row => row.max_amount,
    },
    {
      name: 'Min amount',
      selector: row => row.min_amount,
    },
    {
      name: 'pair',
      selector: row => row.pair,
    },
    {
      name: 'provider',
      selector: row => row.provider,
    },
    {
      name: 'rate',
      selector: row => row.rate,
    },
    {
      name: 'url',
      selector: row => row.url,
    }
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Lightning bridge marketplace
        </h1>

        <button className={styles.button} onClick={() => {console.log(tableData); settestText('hello')}}>
          Hello
          </button>
        <p className={styles.description}>
          This website is collection of Lightning bridges. It is a place where you can find all the information about the bridges. You can also find the bridge you are looking for.
        </p>

        { tableData != undefined && <DataTable
          columns={columns}
          data={tableData}
        />
        }


      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
