import type { NextPage } from "next";
import Head from 'next/head';
import DataTable from 'react-data-table-component';
import { useEffect, useState } from 'react';

export interface DataRow {
  provider : string
  min_amount : string
  max_amount : string
  fee : string
  rate : string
  pair : string
  url : string
}

const Home: NextPage = () => {

  const [tableData, setTableData] = useState<DataRow[]>([]);

  useEffect(() => {
    getData();
}, [])

  const getData = () => {
    fetch('https://lnsov.ml:9001/getpairs')
      .then(response => response.json())
      .then(data => {
        let pairs = data.pairs;
        Object.entries(pairs).map(([key, value] : any) => {
          setTableData(tableData => [...tableData,{
            fee : value.fees.percentage + "%",
            max_amount : value.limits.maximal,
            min_amount : value.limits.minimal,
            pair : key,
            provider : "https://lnsov.vercel.app/",
            rate : value.rate,
            url : "https://lnsov.ml:9001",
          }] );
      });
    });
  }

  const columns = [
    {
      name: 'provider',
      selector: (row: DataRow ) => row.provider,
      button: true,
      wrap: true,
      minWidth: '160px',
    },
    {
      name: 'Fee',
      selector: (row: DataRow) => row.fee,
    },
    {
      name: 'Max amount',
      selector: (row: DataRow) => row.max_amount,
    },
    {
      name: 'Min amount',
      selector:  (row: DataRow) => row.min_amount,
    },
    {
      name: 'pair',
      selector: (row: DataRow) => row.pair,
    },
    {
      name: 'rate',
      selector:  (row: DataRow) => row.rate,
    },
    {
      name: 'url',
      selector:  (row: DataRow) => row.url,
    }
  ];

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-5xl text-center mt-36">
          Lightning bridge marketplace
        </h1>

        <p className="text-xl mt-2 text-center">
          This website is collection of Lightning bridges. It is a place where you can find all the information about the bridges. You can also find the bridge you are looking for.
        </p>

        { tableData != undefined && <DataTable
          columns={columns}
          data={tableData}
        />
        }


      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
